# Jalur absolut ke program pendukung
ffmpeg_path=/usr/bin/ffmpeg
alass_path=/usr/bin/alass

# Mengatur ALASS sebagai program utama untuk sinkronisasi audio
audio_subsync_tool=alass

# Mengatur ALASS untuk sinkronisasi jika mencocokkan antar subtitle
altsub_subsync_tool=alass

# Beritahu MPV untuk melupakan/menghapus track subtitle lama yang tidak pas
unload_old_sub=yes

# Menimpa file subtitle asli dengan hasil yang sudah sinkron (opsional)
# Jika diatur ke "no", skrip akan membuat file baru berakhiran "_retimed.srt"
overwrite_old_sub=no
